name: Package

on:
  push:
    branches: [ runner_branch ]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Building a deb package
        run: ./scripts/package.sh
