name: Test

on:
  push:
    branches: [ runner_branch ]
  workflow_dispatch:
  pull_request:
    branches: [ runner_branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Running tests
        run: ./scripts/test.sh
